name: DevSecOps
'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: null

jobs:
  truffle:
       name: trufflehog-actions-scan
       runs-on: ubuntu-latest
       steps:
       - name: secretsscan
         uses: actions/checkout@master
       - uses: edplato/trufflehog-actions-scan@master
          with:
          scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*

 
