name: DevSecOps
'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: null

jobs:
  Lint:
    name: Sonarscanner for dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '3.1.x' # SDK Version to use.
      - uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
         buildCommand: dotnet build .
         testCommand: dotnet test .
         projectKey: sgs74_nopcommerce
         projectName: nopcommerce
         sonarOrganisation: sgs74
         beginArguments: >
          /d:sonar.verbose="true"
          /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
          /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 
